name: Acquire Activation File
on: workflow_dispatch

jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        uses: game-ci/unity-request-activation-file@v2.1
        with:
          unityVersion: auto 
      - name: Expose as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ManualActivationFile
          path: Unity_v20*.alf
